version: '3.8'

services:
  wallet-api:
    build:
      context: ../ 
      dockerfile: WalletFlow.API/Dockerfile 
    ports:
      - "8080:8080"  
    environment:
      - ASPNETCORE_ENVIRONMENT=Development  
    volumes:
      - .:/app  r
    depends_on:
      - db  
    networks:
      - wallet-net  

  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: walletdb
    ports:
      - "5432:5432"
    networks:
      - wallet-net

networks:
  wallet-net:
    driver: bridge
